name: Keep Render awake

on:
  schedule:
    # 10분마다 실행
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

jobs:
  ping-health:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /api/health
        env:
          BASE_URL: https://jinlotto.onrender.com
        run: |
          set -e
          echo "Pinging $BASE_URL/api/health"
          curl -sS "$BASE_URL/api/health" -m 20 -w " HTTP:%{http_code}\n" || true

